version: '3.2'

services:
  Pump:
    image: digitalplant/pump:latest-minimal
    hostname: Pump
    ports:
      - published: ${PORT}
        target: 1880
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.Type == Pump
    environment:
      - DEVICE_PORT=${PORT}
      - DEVICE_PROXY=${PROXY}
      - DEVICE_NODE={{.Node}}
      - DEVICE_NODE_ID={{.Node.ID}}
      - DEVICE_NODE_HOSTNAME={{.Node.Hostname}}
      - DEVICE_TASK={{.Task}}
      - DEVICE_TASK_NAME={{.Task.Name}}
      - DEVICE_TASK_SLOT={{.Task.Slot}}
      - DEVICE_SERVICE={{.Service}}
      - DEVICE_SERVICE_ID={{.Service.ID}}
      - DEVICE_SERVICE_NAME={{.Service.Name}}
      - DEVICE_SERVICE_LABELS={{.Service.Labels}}
